### PR TITLE
feat(cdc): Publish the postgres docker image

### PR DESCRIPTION
**Pull request by fpacifici**
This PR publishes the Docker image that we were already building.

A lot of postgres plugins are distributed as source and then they have to be compiled on the same platform that will run postgres. 
Publishing an image with the plugin pre-built and pre-installed makes this process simpler in development environments and where postgres can run in docker without exotic configuration.
Besides the development environment, I think this could be a convenient approach as a default for self hosted. We would not have to deal with building the plugin on the right platform and then copying on the postgres container.

### CODE REVIEW

**Comment by fpacifici** [comment]
Ok I think I need to switch to GHA first. Converting to draft

**Comment by BYK** [comment]
Isn't there _any_ pre-built Postgres with these plugins installed?

**Comment by fpacifici** [comment]
This is our fork of this plugin. Which by now is substantially different from the original.  So no, there is none.

**Comment by fpacifici** [comment]
We decided for a different approach: publishing the binary artifact for the architectures we support as a github artifact and mount a volume for that. So we do not have to maintain a full postgres image (and keep it secure) in multiple versions.

**Pull request closed without merging**
